# level0 - the text editor for OSM data, OGF fork at
# https://github.com/opengeofiction-net/level0. PHP via php-fpm.
<VirtualHost *:80>
    ServerName level0.opengeofiction.net
    ServerAdmin sysadmin@opengeofiction.net
    DocumentRoot /var/www/html/level0.opengeofiction.net/web

    ErrorLog /var/www/html/level0.opengeofiction.net/logs/error.log
    CustomLog /var/www/html/level0.opengeofiction.net/logs/access.log combined

    RequestHeader unset Proxy early

    <Directory /var/www/html/level0.opengeofiction.net/web>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html
    </Directory>
</VirtualHost>
